# Model and dataset
model: "DenseNet169"
dataset: "PACS"

# Training hyperparameters
lr: 1e-3
batch_size: 48
momentum: None
weight_decay: 0
epochs: 50
eps: 1e-8
betas: [0.99, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "adam"
nesterov: false

# Early stopping and scheduling
use_early_stopping: true
patience: 3
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: false

# Experiment details
experiment: "densenet169-baseline-pacs"
num_runs: 10
