# Model and dataset
model: "DenseNet121"
dataset: "PACS"
dataset_dir: "datasets"



# Training hyperparameters
lr: 1e-3
batch_size: 48
momentum: 0.9
weight_decay: 0
epochs: 50
eps: 1e-8
betas: [0.99, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "adamw"
nesterov: false

# Early stopping and scheduling
use_early_stopping: true
patience: 3
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
log_dir: "experiments"
experiment: "densenet121-pt-mixstyle-pacs"
num_runs: 1

mixstyle_layers: ['DenseBlock_1', 'DenseBlock_2']
mixstyle_alpha: 0.3
mixstyle_p: 0.5
mix_type: "crossdomain"
visualize_latent: false
