# Model and dataset
model: "ResNet18"
dataset: "camelyon17"
dataset_dir: "datasets"

# Training hyperparameters
lr: 0.001
batch_size: 64
epochs: 50
eps: 1e-8
betas: [0.9, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "sgd"

# Early stopping and scheduling
use_early_stopping: true
patience: 8
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
log_dir: "experiments"
experiment: "resnet18-pt-mixstyle-camelyon17-l1l2"
num_runs: 10

# Augmentations
augmentation_strategy: "mixstyle"
use_mixstyle: true
mixstyle_layers: ['layer1', 'layer2']
mixstyle_alpha: 0.3
mixstyle_p: 0.5
mix_type: "random"
visualize_latent: false