[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "domgen"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["domgen"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
