# Model and dataset
model: "ResNet18"
dataset: "PACS"

# Training hyperparameters
lr: 1e-3
batch_size: 64
momentum: None # not used
weight_decay: 0.1
epochs: 50
eps: 1e-8
betas: [0.9, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "adamw"
nesterov: None # not used

# Early stopping and scheduling
use_early_stopping: true
patience: 4
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: false

# Experiment details
experiment: "resnet18-baseline-pacs"
num_runs: 10

