# Model and dataset
model: "ResNet18"
dataset: "PACS"
dataset_dir: "datasets"

# Training hyperparameters
lr: 1e-3
batch_size: 64
momentum: 0.9 # not used
weight_decay: 0
epochs: 50
eps: 1e-8
betas: [0.9, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "sgd"
nesterov: None # not used

# Early stopping and scheduling
use_early_stopping: true
patience: 10
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
log_dir: "experiments"
experiment: "resnet18-pt-mixstyle-pacs"
num_runs: 10

# Augmentations
mixstyle_layers: ['layer1', 'layer2', 'layer3']
mixstyle_alpha: 0.3
mixstyle_p: 0.5
mix_type: "random"
visualize_latent: false