# Model and dataset
model: "ResNet18"
dataset: "PACS"
dataset_dir: "datasets"

# Training hyperparameters
lr: 0.001
batch_size: 32
momentum: 0.9 # not used
weight_decay: 0
epochs: 50
eps: 1e-8
betas: [0.9, 0.999]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "sgd"
nesterov: None # not used

# Early stopping and scheduling
use_early_stopping: true
patience: 6
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
log_dir: "experiments"
experiment: "resnet18-pt-custom-masking_color-pacs"
num_runs: 10

# Augmentations
augmentation_strategy: "pacs_custom"
aug_dict: "masking_color"