lr:
  - 1e-5
  - 1e-4
  - 1e-3
  - 1e-2
  - 1e-1
momentum:
  min: 0.1
  max: 0.95
batch_size:
  - 8
  - 16
  - 32
  - 64
  - 128
weight_decay:
  min: 1e-6
  max: 1e-2
criterion:
  - cross_entropy
optimizer:
  - sgd
  - adam
  - adamw
betas:
  - [0.9, 0.999]
  - [0.8, 0.888]
  - [0.85, 0.95]
eps:
  - 1e-8
  - 1e-7
  - 1e-6
nesterov:
  - true
  - false
