# Model and dataset
model: "densenet169"
dataset: "PACS"

# Training hyperparameters
lr: 1e-4
batch_size: 48
momentum: None # not used
weight_decay: 0.003
epochs: 10
eps: 1e-8
betas: [0.9, 0.95]

# Optimization and loss
criterion: "cross_entropy"
optimizer: "adamw"
nesterov: None # not used

# Early stopping and scheduling
use_early_stopping: true
patience: 4
use_scheduling: false

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
experiment: "densenet169-pt-baseline-pacs"
num_runs: 10
