# Model and dataset
model: "ResNet18"
dataset: "camelyon17"
dataset_dir: "datasets"

# Training hyperparameters
lr: 0.001
batch_size: 64
epochs: 50
eps: 1e-8

# Optimization and loss
criterion: "cross_entropy"
optimizer: "sgd"

# Early stopping and scheduling
use_early_stopping: true
patience: 6
use_scheduling: true

# Device and pretraining
device: "cuda"
pretrained: true

# Experiment details
log_dir: "experiments"
experiment: "resnet18-pt-randaugment-camelyon17"
num_runs: 10

# Augmentations
augmentation_strategy: "randaugment"
num_ops: 3